site:
  title: "DocForge Docs"
  description: "Simple static docs."

navigation:
  search: true

footer:
  links:
    - text: "GitHub"
      url: "https://github.com/yourusername/DocForge"
    - text: "License"
      url: "/license.html"
