site:
  title: "Archivox Docs"
  description: "Simple static docs."

navigation:
  search: true

footer:
  links:
    - text: "GitHub"
      url: "https://github.com/yourusername/Archivox"
    - text: "License"
      url: "/license.html"
