site:
  title: "Archivox Docs"
  description: "Simple static docs."

navigation:
  search: true

footer:
  links:
    - text: "GitHub"
      url: "https://github.com/yourusername/Archivox"
    - text: "Tip Jar"
      url: "https://nostrtipjar.netlify.app/?n=npub15jnttpymeytm80hatjqcvhhqhzrhx6gxp8pq0wn93rhnu8s9h9dsha32lx"
